### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by awinogradov** [bem-incubator/bem-forms#12]

**Comment by verybigman** [comment]
1. Пример с доопределением `form-field` и `form` для показа сообщений по фокусу, блюру и сабмите.

**Comment by zxqfox** [comment]
@andrewblond Can you help us with that? I think we need the same tools set as used in bem-components.

**Comment by verybigman** [comment]
Yes, but now enb-bem-specs with bug https://github.com/enb-bem/enb-bem-specs/issues/16. I can connect all tools. This is simply

**Comment by zxqfox** [comment]
But what about magic-platform? ;-)

**Comment by verybigman** [comment]
enb-bem-specs inside)))
