### ISSUE TITLE
Dynamic validators

### ISSUE THREAD

**Issue by awinogradov** [bem-incubator/bem-forms#121]
- [ ] - add validator
- [ ] - remove validator
- [ ] - update values of validator

**Comment by zxqfox** [comment]
Сомнительная штука, can you elaborate?

**Comment by verybigman** [comment]
I can everythink!!!

**Comment by s-panferov** [comment]
> Сомнительная штука, can you elaborate?

+1

**Comment by zxqfox** [comment]
> I can everythink!!!

:smirk_cat: И все же ;-) Каков кейс?

**Comment by verybigman** [comment]
В зависимости от выбора юзера в определенных филдах, валидация в других может изменятся. Как сам валидатор так и его параметры.

**Comment by zxqfox** [comment]
:+1: да, точно. Ларчик просто открывался ;-)

А это не решается кастомными валидаторами, которые флажок проверяют?

**Comment by verybigman** [comment]
Кажется, что нет. На самом деле пока хватит только методов на изменение параметров валидатора
