### ISSUE TITLE
Support bem-tools

### ISSUE THREAD

**Issue by zxqfox** [bem-incubator/bem-forms#126]

**Comment by Guria** [comment]
does it actual since bem-tools uses enb for build process? seems all what we need is `.bem/level.js` files

**Comment by tadatuta** [comment]
+1

**Comment by verybigman** [comment]
all we need is :heart:

**Comment by voischev** [comment]
+1

**Comment by awinogradov** [comment]
@zxqfox we need this?

**Comment by tadatuta** [comment]
@awinogradov definitely no

**Comment by awinogradov** [comment]
@tadatuta cool!
