### ISSUE TITLE
Add possibility to suppress change event while calling setVal()

### ISSUE THREAD

**Issue by s-panferov** [bem-incubator/bem-forms#136]
There are a lot of cases when I don't want my controls to emit 'change' event while I call `setVal`, e.g. when I fill/restore form state using some external data.

It can be added in backwards compatible way by adding one more optional argument to `setVal`: `setVal(val, emitChange = true)`

**Comment by verybigman** [comment]
:+1:

**Comment by s-panferov** [comment]
@verybigman but I think that you can't do this without rewriting bem-components.

**Comment by tadatuta** [comment]
that's exactly the reason to build additional layer on top of controls from `bem-components` (and not to emit additional events right inside of them ;))
