### ISSUE TITLE
Метод установки статуса form-field

### ISSUE THREAD

**Issue by kompolom** [bem-incubator/bem-forms#152]
Используется валидация на сервере. как установить неправильному form-field соответствующий статус? 
Метод `getStatus` есть. А `setStatus` ?

**Comment by awinogradov** [comment]
Стутус устанавливается только по результату валидатации. Валидатор возвращает сообщение и оно устанавливается в статус. Если надо установить только видимое сообщение, то есть метод setMessageVal.

**Comment by kompolom** [comment]
@awinogradov Ок. Как быть, если валидация на сервере?

**Comment by awinogradov** [comment]
Писать валидатор, который ходит на сервер и ставит статус) form-feild_validate_server

**Comment by kompolom** [comment]
@awinogradov А чем хорош такой подход? Мне вот кажется что на каждое поле тратить лишний запрос к бэкенду - вообще не красиво. Гораздо проще отправить всю форму, а ошибки, если есть получить объектом, потом расставить статусы полям. Не так ли?

**Comment by awinogradov** [comment]
@kompolom сорри за долгий ответ. Смотря какая форма. Форма может быть из большого количество полей с одним серверным валидатором. В целом я не против наличия такого метода. Можно переименовать issue и поставить тег;)
