### ISSUE TITLE
BH support

### ISSUE THREAD

**Issue by awinogradov** [bem-incubator/bem-forms#168]
We need BH support in this lib? 

cc @tadatuta @zxqfox

**Comment by tadatuta** [comment]
yes, we have support for both template engines in `bem-core` and `bem-components` so it should be here as well.

**Comment by tadatuta** [comment]
please consider using https://github.com/vkz/bemhtml-source-convert for automatic conversion (and let us know if it really works ;))

**Comment by awinogradov** [comment]
@tadatuta ok

**Comment by zxqfox** [comment]
Ащь.

**Comment by JiLiZART** [comment]
Really need this ;)

**Comment by voischev** [comment]
@JiLiZART you use bem-forms?)

**Comment by zxqfox** [comment]
will do in a week
